version: "3.2"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: project
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=db
    volumes:
      - .:/var/www/html/
    ports:
      - "80:80"
    container_name: proj
  mysql:
    image: mysql:5.7
    environment: 
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=db
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
    container_name: db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    ports:
      - "8082:80"
    environment: 
      - PMA_HOST=mysql
      - PMA_PORT=3306
    volumes:
      - /sessions
    container_name: phpmyadmin
volumes:
  mysql_volume:
