version: "3.2"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: project
    env_file:
    - compose.env
    environment:
     - compose.env
    volumes:
      - .:/var/www/html/
    ports:
      - "80:80"
      - "8000:8000"
      - "9000:9000"
    container_name: proj
  mysql:
    image: mysql:5.7
    ports:
    - "3306:3306"
    env_file:
      - compose.env
    environment:
      - compose.env
    volumes:
      - mysql_volume:/var/lib/mysql
    container_name: db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    ports:
      - "8082:8082"
    env_file:
    - compose.env  
    environment:
    - compose.env
    volumes:
      - /sessions
    container_name: phpmyadmin
volumes:
  mysql_volume:
